# Generated by Django 4.2.3 on 2023-12-13 13:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_myuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MyUser',
        ),
    ]
