# Generated by Django 4.2.3 on 2023-12-22 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_category_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerpurchase',
            name='email',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
