# Generated by Django 4.2.3 on 2023-12-13 13:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_myuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MyUser',
        ),
    ]
