# Generated by Django 4.2.3 on 2023-12-16 12:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_alter_customerpurchase_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerpurchase',
            name='product',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.product'),
            preserve_default=False,
        ),
    ]
