# Generated by Django 4.2.3 on 2023-12-16 12:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_alter_customerpurchase_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerpurchase',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.product'),
        ),
    ]
