# Generated by Django 4.2.3 on 2023-12-16 12:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_alter_customerpurchase_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customerpurchase',
            name='product',
        ),
        migrations.RemoveField(
            model_name='customerpurchase',
            name='quantity',
        ),
        migrations.CreateModel(
            name='PurchaseItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('customer_purchase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.customerpurchase')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.product')),
            ],
        ),
        migrations.AddField(
            model_name='customerpurchase',
            name='products',
            field=models.ManyToManyField(through='app.PurchaseItem', to='app.product'),
        ),
    ]
