# Generated by Django 4.2.3 on 2023-12-16 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_remove_customerpurchase_product_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerpurchase',
            name='total_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='customerpurchase',
            name='total_quantity',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
